### ISSUE TITLE
MountPoints in container configs are not mounted by docker-explorer

### ISSUE THREAD

**Issue by sa3eed3ed** [google/docker-explorer#108]
Docker Explorer didn't mount the mount points inside the container config file and I had to mount it manually. Here is a redacted copy of the config file.
```
"MountPoints": {
        "/var/www/html": {
            "Destination": "/var/www/html",
            "Driver": "local",
            "ID": "[VOLUME_ID]",
            "Name": "[VOLUME_NAME]",
            "RW": true,
            "SkipMountpointCreation": false,
            "Source": "",
            "Spec": {},
            "Type": "volume"
        }
```
* Docker automatically mount `/var/www/html` to `/media/disk/var/lib/docker/volumes/[VOLUME_NAME]/_data` however docker explorer didn't do it as part of the container mount operation, and I had to do it manually.

**Comment by rgayon** [comment]
Fixed in https://github.com/google/docker-explorer/pull/110
