### ISSUE TITLE
mountID not set on docker v1

### ISSUE THREAD

**Issue by paradoxengine** [google/docker-explorer#46]
I might be misreading the code, but I can't see where mount_id is set in the container if docker version == 1.
I only see mount_id set here: https://github.com/google/docker-explorer/blob/8f51e662d4ad0a3e43bfb1d38ab891067e23f667/docker_explorer/lib/container.py#L129 
in a branch of code that gets triggere on Docker v2. Since mount_id is used widely across the various build commands, do they actually work against V1? Is it expected that it might be null? (I do not have a Docker V1 around to test)

**Comment by rgayon** [comment]
#59 is merged, feel free to reopen if this still looks broken to you :)
