### ISSUE TITLE
aufs mount broken?

### ISSUE THREAD

**Issue by paradoxengine** [google/docker-explorer#48]
Hi,
 I'm not sure the workflow for aufs mount is working as intended?

Looking here:

https://github.com/google/docker-explorer/blob/8f51e662d4ad0a3e43bfb1d38ab891067e23f667/docker_explorer/lib/storage.py#L141

container_id is a path (i.e. there is no file read associated) which is then concatenated to other paths further down the code. That does not seem to be right, so I suspect that is meant to be a file read or something along those lines, but I'm not quite sure what without doing some reversing.

**Comment by rgayon** [comment]
AUFS V1 storage mounting should now work with #59

**Comment by rgayon** [comment]
#58 (for the var name issue) and #59 (AuFS mounting works) are merged, feel free to reopen if this still looks broken to you :)
