### ISSUE TITLE
Support windowsfilter Storage

### ISSUE THREAD

**Issue by rgayon** [google/docker-explorer#50]
https://github.com/moby/moby/blob/8c0d7e6d52ea04a1523944dda8c6e168dc785ae2/daemon/graphdriver/windows/windows.go

**Comment by rgayon** [comment]
In the case of DockerDesktop, docker is run within WSL. So the data is in an HyperV disk image  in C:\Users\<user>\AppData\Local\Docker\wsl\data\ext4.vhdx, where all docker stuff is being run.

Once [mounted](https://stackoverflow.com/a/37790474), docker-explorer can be run and list containers:de.py -r /mnt/version-pack-data/community/docker list all_containers

**Comment by jonathan-greig** [comment]
Closed with #117 and #118
