### ISSUE TITLE
Go from overlayFS ID to container ID

### ISSUE THREAD

**Issue by tomchop** [google/docker-explorer#55]
It would be useful to find a way to map an overlayFS ID to the container that actually used it.

e.g. given this path on a server running Docker:

`/mnt/docker/var/lib/docker/overlay2/6688ce711806faead06aae3ff534ab21183a087241d3a890741f0c3b437b179c/diff/var/tmp/malware`

Find out in which container 6688ce711806faead06aae3ff534ab21183a087241d3a890741f0c3b437b179c is being used.

**Comment by rgayon** [comment]
This needs #28 to be fixed first :(
